server:
  port: 8081

spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  data:
    redis:
      host: 192.168.100.104
      port: 6379
      password: xgw18720322169.
      database: 1

short-link:
  stats:
    local:
      amap-key: 24edb97310c8d94e4b0435486db840cf